[package]
name = "rlirsh"
version = "0.1.0"
authors = ["gifnksm <makoto.nksm+github@gmail.com>"]
edition = "2018"
description = "Rootless insecure remote shell"
repository = "https://github.com/gifnksm/rlirsh"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
